name: Deploy Rookie Engine

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y cmake g++

    - name: Configure CMake (Release)
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build engine
      run: cmake --build build --verbose

    # - name: List files after build
    #   run: ls -al bin

    - name: Copy engine to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "source/rookie_engine"
        target: "/var/www/portfolio/rookie-app/engine/rookie-engine"

    - name: Set executable permissions
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          chmod +x /var/www/portfolio/rookie-app/engine/rookie-engine
